const http=require("http"),https=require("https"),bcrypt=require("bcrypt"),querystring=require("querystring"),router=require("find-my-way")(),Database=require("./lib/database.js");let informationDatabase=new Database,internetProtocolAddressed=new Database,globalPassword;const bodyParse=async e=>new Promise((t,a)=>{let r="";e.on("data",e=>{r+=e}),e.on("error",()=>{a("Something happened.")}),e.on("end",()=>{t(r)})});router.on("GET","/health",(e,t)=>{informationDatabase?(t.writeHead(200,{"Content-Type":"application/json"}),t.end(`{
            "status": "Active",
            "details": "Database/Map Working"
        }`)):(t.writeHead(200,{"Content-Type":"application/json"}),t.end(`{
            "status": "Active",
            "details": "Database/Map Not Working"
        }`))}),router.on("GET","/cr",async(e,t)=>{t.writeHead(200,{"Content-Type":"text/html"}),t.end(`
        <form action="/create-table" method="post">
            <label for="password">Password:</label><br>
            <input type="password" id="password" name="password">
            <label for="name">Name:</label><br>
            <input type="text" id="name" name="name">
            <input type="submit" value="Submit">
        </form>
    `)}),router.on("POST","/create-table",async(e,t)=>{let a=await bodyParse(e),r=querystring.parse(a);r.password==globalPassword?(informationDatabase.createTable(r.name),t.writeHead(201,{"Content-Type":"text/plain"}),t.end("Created")):(t.writeHead(403,{"Content-Type":"text/plain"}),t.end("Forbidden"))}),router.on("POST","/set-resource",async(e,t)=>{let a=await bodyParse(e),r=querystring.parse(a);r.password==globalPassword?(informationDatabase.setResource(r.tableID,r.key,r.value),t.writeHead(201,{"Content-Type":"text/plain"}),t.end("Created")):(t.writeHead(403,{"Content-Type":"text/plain"}),t.end("Forbidden"))}),router.on("POST","/get-resource",async(e,t)=>{let a=await bodyParse(e),r=querystring.parse(a);r.password==globalPassword?(t.writeHead(200,{"Content-Type":"text/plain"}),t.end(informationDatabase.getResource(r.tableID,r.key))):(t.writeHead(403,{"Content-Type":"text/plain"}),t.end("Forbidden"))}),router.on("POST","/get-table-size",async(e,t)=>{let a=await bodyParse(e),r=querystring.parse(a);r.password==globalPassword?(t.writeHead(200,{"Content-Type":"text/plain"}),t.end(informationDatabase.getTableSize(r.tableID))):(t.writeHead(403,{"Content-Type":"text/plain"}),t.end("Forbidden"))}),router.on("POST","/delete-resource",async(e,t)=>{let a=await bodyParse(e),r=querystring.parse(a);r.password==globalPassword?(informationDatabase.deleteResource(r.tableID,r.key),t.writeHead(200,{"Content-Type":"text/plain"}),t.end("Deleted")):(t.writeHead(403,{"Content-Type":"text/plain"}),t.end("Forbidden"))});class HttpBlackBase{constructor(e){globalPassword=e,this.server=http.createServer((e,t)=>{router.lookup(e,t)}),process.on("exit",function(){req.off("data"),router.off("GET","/health"),router.off("GET","/create-table")})}listen(e){this.server.listen(e)}}module.exports={HttpBlackBase};